repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
  - repo: https://github.com/psf/black
    rev: 23.9.1 
    hooks:
      - id: black
        language_version: python3