version: '3.8'

services:
  postgresql-primary:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgresql_master_data:/var/lib/postgresql/data

  couchdb:
    image: couchdb:3.3.2
    container_name: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      - subnet

volumes:
  postgresql_master_data:
  couchdb_data:

networks:
  subnet:
    driver: bridge
