default_args:
  owner: "airflow"
  start_date: "2025-02-24"
  retries: 1
  retry_delay: 300

dags:
  bronze:
    schedule_interval: "@daily"
    catchup: False
    tables:
      - accounts_created
      - accounts_deleted
      - accounts_updated
      - audits
      - claims
      - credit_scores
      - entities
      - insured_entities
      - loans
      - merchants
      - payment_methods
      - payment
      - policies
      - portfolios
      - regulations
      - risk_assessments
      - subaccounts
      - transactions
      - user_verifications
      - users

  silver:
    schedule_interval: "@daily"
    catchup: False
    tables:
      - accounts
      - audits
      - claims
      - credit_scores
      - entities
      - insured_entities
      - loans
      - merchants
      - payment_methods
      - payment
      - policies
      - portfolios
      - regulations
      - risk_assessments
      - subaccounts
      - transactions
      - user_verifications
      - users

  gold:
    schedule_interval: "@daily"
    catchup: False
    tables:
      - accounts
      - audits
      - claims
      - credit_scores
      - entities
      - insured_entities
      - loans
      - merchants
      - payment_methods
      - payment
      - policies
      - portfolios
      - regulations
      - risk_assessments
      - subaccounts
      - transactions
      - user_verifications
      - users
