default_args:
  owner: "airflow"
  start_date: "2025-02-24"
  retries: 1
  retry_delay: 300

dags:
  bronze:
    schedule_interval: "@daily"
    catchup: False
    tables:
      - accounts_created
      - accounts_deleted
      - accounts_updated
      - audits_created
      - audits_deleted
      - audits_updated
      - claims_created
      - claims_deleted
      - claims_updated
      - credit_scores_created
      - credit_scores_deleted
      - credit_scores_updated
      - entities_created
      - entities_deleted
      - entities_updated
      - insured_entities_created
      - insured_entities_deleted
      - insured_entities_updated
      - loans_created
      - loans_deleted
      - loans_updated
      - merchants_created
      - merchants_deleted
      - merchants_updated
      - payment_methods_created
      - payment_methods_deleted
      - payment_methods_updated
      - payment_created
      - payment_deleted
      - payment_updated
      - policies_created
      - policies_deleted
      - policies_updated
      - portfolios_created
      - portfolios_deleted
      - portfolios_updated
      - regulations_created
      - regulations_deleted
      - regulations_updated
      - risk_assessments_created
      - risk_assessments_deleted
      - risk_assessments_updated
      - subaccounts_created
      - subaccounts_deleted
      - subaccounts_updated
      - transactions_created
      - transactions_deleted
      - transactions_updated
      - user_verifications_created
      - user_verifications_deleted
      - user_verifications_updated
      - users_created
      - users_deleted
      - users_updated

  silver:
    schedule_interval: "@daily"
    catchup: False
    tables:
      - accounts_created
      - accounts_deleted
      - accounts_updated
      - audits_created
      - audits_deleted
      - audits_updated
      - claims_created
      - claims_deleted
      - claims_updated
      - credit_scores_created
      - credit_scores_deleted
      - credit_scores_updated
      - entities_created
      - entities_deleted
      - entities_updated
      - insured_entities_created
      - insured_entities_deleted
      - insured_entities_updated
      - loans_created
      - loans_deleted
      - loans_updated
      - merchants_created
      - merchants_deleted
      - merchants_updated
      - payment_methods_created
      - payment_methods_deleted
      - payment_methods_updated
      - payment_created
      - payment_deleted
      - payment_updated
      - policies_created
      - policies_deleted
      - policies_updated
      - portfolios_created
      - portfolios_deleted
      - portfolios_updated
      - regulations_created
      - regulations_deleted
      - regulations_updated
      - risk_assessments_created
      - risk_assessments_deleted
      - risk_assessments_updated
      - subaccounts_created
      - subaccounts_deleted
      - subaccounts_updated
      - transactions_created
      - transactions_deleted
      - transactions_updated
      - user_verifications_created
      - user_verifications_deleted
      - user_verifications_updated
      - users_created
      - users_deleted
      - users_updated

  gold:
    schedule_interval: "@daily"
    catchup: False
    tables:
      - accounts
      - audits
      - claims
      - credit_scores
      - entities
      - insured_entities
      - loans
      - merchants
      - payment_methods
      - payment
      - policies
      - portfolios
      - regulations
      - risk_assessments
      - subaccounts
      - transactions
      - user_verifications
      - users
