version: '3.8'

services:
  postgresql-primary:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgresql_master_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    command: >
      postgres -c wal_level=logical
               -c max_wal_senders=5
               -c max_replication_slots=5
               -c shared_preload_libraries='test_decoding'

  postgresql-replica:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    depends_on:
      - postgresql-primary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgresql_replica_data:/var/lib/postgresql/data
    command: >
      postgres -c wal_level=logical
               -c max_wal_senders=5
               -c max_replication_slots=5

  couchdb:
    image: couchdb:3.3.2
    container_name: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      - etl_network

  api:
    build: .
    container_name: api_service
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgresql-primary
      - couchdb
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgresql-primary:5432/postgres
      COUCHDB_URL: http://admin:password@couchdb:5984/
    networks:
      - etl_network

volumes:
  postgresql_master_data:
  postgresql_replica_data:
  couchdb_data:

networks:
  etl_network:
    driver: bridge
