name: Terraform CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Plan Terraform changes
        run: terraform plan -out=tfplan
        working-directory: terraform

      - name: Apply Terraform changes
        run: terraform apply -auto-approve
        working-directory: terraform

      - name: Clean up Terraform temporary files
        run: rm -f tfplan
        working-directory: terraform
        if: always()

      - name: Store Terraform state (if needed)
        run: |
            if [ -f terraform.tfstate ]; then
              gsutil cp terraform.tfstate gs://${{ secrets.TERRAFORM_BUCKET }}/terraform/state/
            else
              echo "No terraform.tfstate found, skipping upload."
            fi
        working-directory: terraform
        if: always()